name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils genisoimage

      - uses: actions/checkout@v4

      - name: Build image
        run: |
          wget https://raw.githubusercontent.com/alpinelinux/alpine-make-vm-image/v0.13.2/alpine-make-vm-image \
            && echo '2720b23e4c65aff41a3ab781a26467b66985c526 alpine-make-vm-image' | sha1sum -c \
            || exit 1
          chmod +x ./alpine-make-vm-image
          if command -v sudo >/dev/null 2>&1; then
            ELEVATE="sudo"
          elif command -v doas >/dev/null 2>&1; then
            ELEVATE="doas"
          else
            echo "Neither sudo nor doas found. This script requires root privileges."
            exit 1
          fi
          $ELEVATE ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 1G \
              --repositories-file openstack/repositories \
              --packages "$(cat openstack/packages)" \
              --serial-console \
              --script-chroot \
              alpine-openstack.qcow2 -- ./openstack/configure.sh
          sha256sum alpine-openstack.qcow2 > SHA256SUMS
      - name: Upload QCOW2 root fs artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-openstack.qcow2
          path: "${{ github.workspace }}/alpine-openstack.qcow2"
      - name: Make Development release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            alpine-openstack.qcow2
            SHA256SUMS
  test-image:
    name: Test produced image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: alpine-openstack.qcow2
      - name: Apply plan
        id: apply_plan
        run: |
          cd terraform
          mkdir -p $HOME/.config/openstack
          echo -n "${{ secrets.cloud_config }}" | openssl base64 -d -A > $HOME/.config/openstack/clouds.yaml
          echo -e "${{ secrets.TERRAFORM_VARS }}" | openssl base64 -d -A > terraform.tfvars
          terraform init
          terraform apply -auto-approve
          echo "instance_ipv4=$(terraform output -raw instance_ipv4)" >> $GITHUB_OUTPUT
        env:
          OS_CLOUD: openstack
      - name: Test connectivity of the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.apply_plan.outputs.instance_ipv4 }}
          username: root
          debug: true
          key: ${{ secrets.SSH_KEY }}
          script: |
            apk update && apk upgrade
      - name: Save working image
        run: |
          python -m pip install python-openstackclient
          openstack image delete alpine-openstack-backup || /bin/true
          openstack image set --name alpine-openstack-backup alpine-openstack-latest || /bin/true
          openstack image set --name alpine-openstack-latest alpine-openstack
        env:
          OS_CLOUD: openstack
      - name: Destroy the test VM
        run: |
          cd terraform
          terraform state rm openstack_images_image_v2.alpine
          terraform destroy -auto-approve
        env:
          OS_CLOUD: openstack
